{
    "output_categories" : [4,4],
    "sequence_size":[125],
    "optimizer" : "adam",
    "lr" : 0.0001,
    "purpose": "train",
    "model": "consent_rope_selective",
    "loss_fn": {"train":"single_source_loss_split","val":["single_source_val_loss_split"]},
    "label_split":[[4,4]], 
    "loss_weights":[0.25,0.75],
    "loss_type" :  {"train":["ce","ce"],"val":["ce","ce"]},
    "use_external_sampler":[false],
    "sampler_dataset_fraction":[1],
    "sampler_class_weights" : [[]], 
    "datasets" : {"train":["/ssd_scratch/rohan.kumar/swaroopajinka/corpus_augmented_strikeout_uands_underlined_copied/T2_125/word_CW/train"],"val":["/ssd_scratch/rohan.kumar/swaroopajinka/corpus_augmented_strikeout_uands_underlined_copied/T2_125/word_CW/val"]},
    "batch_size" : 1600,
    "pretrained":"/ssd_scratch/rohan.kumar/swaroopajinka/checkpoints/consent_rebuttal-augmentation_NO-arch-consent_mixed_train_23dec_dropout-best_avg_f1.pt",
    "load_pretrained_function":"freeze",
    "batch_split" : [1600],
    "accumulated_batch_descent" :2,
    "order" : {"train":["error"],"val":["error"]},
    "dataloaders" : {"train" : ["DocLevelDataset_RoPE_Train"], "val" : ["DocLevelDataset_RoPE_Val_name"]},
    "num_workers":8,
    "isWandb":true,
    "run_name":"consent_rebuttal-augmentation_NO-phase2-note-phase2isunweighted",
    "shuffle":[true],
    "wandb_project_name":"T1-9Aug",
    "epochs" : 100,
    "viz_labels":[],
    "multi-gpu" : false
}