generate_json:
  image_folder: "/data/textar_inputs"
  output_json: "/data/textar_outputs/jsons/generate_bbox.json"
  load_fine_tune_model: false
  pretrained_model_path: None
  batch_size: 64
  device: "cuda:0"
  extensions:
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".tiff"
    - ".bmp"

context_crop:
  bbjson: "/data/textar_outputs/jsons/generate_bbox.json"
  image_folder: "/data/textar_inputs"
  output_file_path: "/data/textar_outputs/jsons/crops.json"
  enable_random: 0
  seq_size: 125
  type: "word"
  pad: "y"
  aspect_ratio: 1.3334

extract_cw:
  image_folder: "/data/textar_inputs"
  bbox_json_path: "/data/textar_outputs/jsons/generate_bbox.json"
  cw_json_path: "/data/textar_outputs/jsons/crops.json"
  output_word_crops_path: "/data/textar_outputs/word_only"
  pad_cropped_frame: "y"
  context_window_type: "word CW"
  sequence_size: 100
  aspect_ratio: 1.3334
  word_bbox_padding_offset: 0.1
  extract_attributes:
    T1: true
    T2: true
  
image_organization:
  source_folder: "/data/textar_outputs/word_only/"
  dest_folder: "/data/textar_outputs/word_cw/"